#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage: `basename $0` <HOST_IP> <SERVICE_PASSWORD>"
  exit -1
fi

PORT=8118
HOST=$1 # Put your host IP here
SVC_PASSWD=$2

SERVICE_ID=$(openstack service show playnetmano_rm -f value -cid 2>/dev/null)
if [[ -z $SERVICE_ID ]]; then
  SERVICE_ID=$(openstack service create \
    --name playnetmano_rm \
    --description 'playnetmano_rm Service V1.0' \
    -f value -cid \
    multisite)
fi

if [[ -z $SERVICE_ID ]]; then
  exit
fi

openstack endpoint create \
  --adminurl "http://$HOST:$PORT/v1.0/\$(tenant_id)s" \
  --publicurl "http://$HOST:$PORT/v1.0/\$(tenant_id)s" \
  --internalurl "http://$HOST:$PORT/v1.0/\$(tenant_id)s" \
  --region RegionOne \
  playnetmano_rm

openstack user create \
  --password "$SVC_PASSWD" \
  --project service \
  playnetmano_rm

openstack role add \
  admin \
  --user playnetmano_rm \
  --project service

# make sure 'playnetmano_rm' has 'service' role in 'demo' project
openstack role add \
  service \
  --user playnetmano_rm \
  --project demo
